### ISSUE TITLE
Unsupported file type

### ISSUE THREAD

**Issue by wapisani** [edyoung/gnofract4d#1]
Upon attempting to save current image, I get an error which says that the extension .png is an unsupported file type. Attached is a screenshot of the error message.
![error_upon_saving](https://cloud.githubusercontent.com/assets/12666869/12107821/18f26192-b33e-11e5-930f-0a6bfefab50b.png)

**Comment by edyoung** [comment]
Hi Will,

Most likely you need to install the PNG header files (usually in a package
called libpng-dev) and recompile - if those are not found you get a warning
in the ./setup.py build output and only TGA will be supported.

**Comment by edyoung** [comment]
Checked in a change to fail compilation altogether if these headers are missing, the warning message seems too easy to miss.
