### ISSUE TITLE
yelp bug breaks Help menu

### ISSUE THREAD

**Issue by cjmayo** [edyoung/gnofract4d#17]
"Crashes when loading a uri with subsection"
https://bugzilla.gnome.org/show_bug.cgi?id=770453

Causes Help menu items other than Contents to do nothing.

**Comment by edyoung** [comment]
I'm thinking it might be better to ditch the whole ancient XSL help doc
scheme and switch to something a bit more modern - but haven't really
worked out what the best options are.

**Comment by cjmayo** [comment]
Some suggestions in python3:
da23ae39db04b6802ba845ee1f0fdb88a53f119d - replace command reference help item with ShortcutsWindow
91b4548b0d075c010268d738bbf295993c49009f - remove formula reference help item (alas don't think there is a simple option, it is still in help)

For Help/About, something like this (needs license and copyright info as a minimum)?:
```diff
--- a/fract4dgui/main_window.py
+++ b/fract4dgui/main_window.py
@@ -8,6 +8,7 @@ import re
 from gi.repository import Gdk, Gtk
 
 from fract4d import fractal, fc, image, fracttypes, fractconfig
+from fract4d.options import VERSION
 
 from . import (gtkfractal, model, preferences, autozoom, settings, toolbar,
     browser, fourway, angle, utils, hig, painter, icons, renderqueue, director)
@@ -1412,8 +1413,15 @@ class MainWindow:
                 break
         return True
     
-    def about(self,*args):
-        self.display_help("about")
+    def about(self, *args):
+        aboutDialog = Gtk.AboutDialog.new()
+        aboutDialog.set_transient_for(self.window)
+        aboutDialog.set_modal(True)
+        aboutDialog.set_program_name("Gnofract 4D")
+        aboutDialog.set_version(VERSION)
+        aboutDialog.set_logo_icon_name("gnofract4d")
+        aboutDialog.set_website("https://github.com/edyoung/gnofract4d/")
+        aboutDialog.show()
 
     def quit(self,action,widget=None):
         """Quit Gnofract 4D."""
```

**Comment by edyoung** [comment]
I ditched yelp and launch browser directly for the case where ShortcutsWindow doesn't work
