### ISSUE TITLE
Higher resolution icons for modern desktop

### ISSUE THREAD

**Issue by cjmayo** [edyoung/gnofract4d#19]
e.g. GNOME desktop now displays icons at a much larger size, current one looks a bit fuzzy.

Best to add multiple sizes 16x16, 32x32, 48x48, 64x64, 128x128 and even 256x256 and install in
`/usr/share/icons/hicolor/[size]/apps`
https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-icon-list

**Comment by cjmayo** [comment]
I think ideally it would be something drawn using Gnofract 4D, which would also be reproducible later. I had a go and came up with:

file:///srv/open/github/gnofract4d/logo/128/gnofract4d-logo.png

still looks recognisable at smallest size:

file:///srv/open/github/gnofract4d/logo/16/gnofract4d-logo.png

Happy if there are better candidates than these, just a suggestion.

**Comment by jamesjer** [comment]
We would really like an icon that is a minimum of 64x64 for Fedora, too.  @cjmayo those icons you created are given with file:// links.  Are they online somewhere?  Thank you.

**Comment by cjmayo** [comment]
Should be there now. Just had to work out which bit of security was blocking the upload!

**Comment by jamesjer** [comment]
Yes, that worked.  Thank you!

**Comment by edyoung** [comment]
I replaced gnofract4d-logo with the new one you generated. thanks!
