### ISSUE TITLE
Setup.py won't build on python 3.5.1

### ISSUE THREAD

**Issue by ConnectedReasoning** [edyoung/gnofract4d#3]
wont run on python 3.5.1.

$ ./setup.py build
  File "./setup.py", line 14
    print "Sorry, you need Python 2.4 or higher to run Gnofract 4D."
                                                                   ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by edyoung** [comment]
Yes; the whole project is still python2. It might work after running through python2to3 tool, I haven't tried. I'm afraid I don't have time to change that, but would take pull requests to do so.

**Comment by edyoung** [comment]
I started a branch to move everything to python3 (seems about time) and got about 75% done but this effort is still incomplete. I mention it just in case there's someone who gets the urge to look at this.

**Comment by edyoung** [comment]
The latest release runs on python 3. Better late than never...
