### ISSUE TITLE
Gnofract4d is too hard to install on WSL

### ISSUE THREAD

**Issue by mathieucaroff** [edyoung/gnofract4d#37]
I use WSL and some packages really take time to find. This is the case for `python3-gi-cairo`. Their names could be mentionned in the README rather than having the user find each of them one by one.

```bash
$ uname -rp
4.4.0-17134-Microsoft x86_64
$ lsb_release -cds
Ubuntu 18.04.1 LTS
bionic
```

Here is the full list of packages I had to install before it could show me a fractal:

```bash
sudo apt install libpng-dev libjpeg-dev gtk3.0 cairo python3-cairo python3-gi-gairo
```

And still, the application is not fully working. For instance, the entries "Contents" and "About" from the help menu don't work. I also experienced a crash.

Note: `libpng-dev` and `libjpeg-dev` where mandatory, not optional.

**Comment by edyoung** [comment]
To be honest I didn't realize it was possible to run GUI programs in WSL. I will add a note to the README. Feel free to edit the Wiki with any other WSL tips you have.
