### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by iaraUM** [edyoung/gnofract4d#49]
When i put "python setup.py install" say me this:

PS D:\VCE-Master\ProgramInst\gnofract4d-4.0.1> python setup.py install
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    os.environ["CFLAGS"]= distutils.sysconfig.get_config_var("CFLAGS").replace("-Wstrict-prototypes","")
AttributeError: 'NoneType' object has no attribute 'replace'
PS D:\VCE-Master\ProgramInst\gnofract4d-4.0.1>

How to fix?

**Comment by edyoung** [comment]
Try python3 setup.py install
