### ISSUE TITLE
Adding arbitrary precision math support using GMP

### ISSUE THREAD

**Issue by mindhells** [edyoung/gnofract4d#51]
Hi,

what is the actual status of the gmp support?

I saw there's some mentions in the `setup.py` regarding this matter and also some files under `fract4d/c` with that suffix (those files seem to be unmaintained copies of the same file without the suffix).

**Comment by edyoung** [comment]
It's nonexistent. I once tried to implement GMP support but it never got close to completion. Sorry. Will happily take pull requests ;-)

**Comment by mindhells** [comment]
That's the idea, I want to contribute on the topics described on ["help wanted"](http://edyoung.github.io/gnofract4d/contributing.html) section. 

In this particular topic, as I mentioned above there's some hanging files but I can't see any meaning on them. Can you confirm these are just unmaintained copies (`*_gmp.cpp` files under `fract4d/c`)? If that is so then maybe the 1st step it's to remove them. 

The codebase it's huge, I've been looking at it and it looks like a long term task to get to add this kind of functionality. The interfaces between python and C++ (fract4dmodule) are a bit messy, I think the best approach would be start with a refactor. It would be great to organize the code in different packages regarding its responsibility (for example the compiler, the user configuration...) to isolate them, if we get to identify the interfaces, so in the future it's easy to maintain.
What do you think?

I'm getting to know how everything works and trying to make little progress on some minor topics. You'll be hearing from me the coming weeks.

**Comment by edyoung** [comment]
Hi Alberto,

Sounds good to me. Yes, the _gmp files are probably just junk at this
point. I no longer really have the time to do any significant work on this
project (which started almost 20 years ago) so happy to take improvements
and other changes anyone wants to contribute. The main division now is
between UX code (which depends on GTK) in fract4dgui and UX-neutral code in
fract4d.
