### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by Ravenmire** [edyoung/gnofract4d#8]
[ted@Server gnofract4d-master]$ ./setup.py build
  File "./setup.py", line 14
    print "Sorry, you need Python 2.4 or higher to run Gnofract 4D."
                                                                   ^
SyntaxError: Missing parentheses in call to 'print'
[ted@Server gnofract4d-master]$ python --version
Python 3.6.2
[ted@Server gnofract4d-master]$ 

Hardly an auspicious beginning.

**Comment by edyoung** [comment]
Gnofract 4D uses python 2.x at present, since it predates the existence of
Python 3. Python 3.x introduced substantial breaking changes to the
language and isn't compatible. So use python 2.x, or if you're more
ambitious fix the work in progress python3 branch and send a pull request.

**Comment by Ravenmire** [comment]
The message is misleading. 3.x > 2.6.
Can the program detect python3, issue a meaningful message, and quit?
I have python 2. It can be executed as python2.
[ted@Server gnofract4d-master]$ python2
Python 2.7.13 (default, Jul 21 2017, 03:24:34)
[GCC 7.1.1 20170630] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
[ted@Server gnofract4d-master]$
Given the power of Python, it should be able to handle this case.
I am not a Python programmer; I expect programs to "just work". Silly, I know.
I am a programmer. I also believe that programs should work for people, not the other way around.

Ted, M∴ M∴
--

GnuPG/PGP key: 0xb07f9aae
Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by Ravenmire** [comment]
How I got it to work:
cd /usr/sbin
mv -v python python3
mv -v python2 python
cd to gnofract4d-master
setup.py build
./gnofract4d

Ted, M∴ M∴
--

GnuPG/PGP key: 0xb07f9aae
Sent with [ProtonMail](https://protonmail.com) Secure Email.

> -------- Original Message --------
> Subject: Re: [edyoung/gnofract4d] Python version (#8)
> Local Time: July 31, 2017 2:47 AM
> UTC Time: July 31, 2017 6:47 AM
> From: notifications@github.com
> To: edyoung/gnofract4d <gnofract4d@noreply.github.com>
> Ravenmire <Ravenmire@ProtonMail.com>, Author <author@noreply.github.com>
> Gnofract 4D uses python 2.x at present, since it predates the existence of
> Python 3. Python 3.x introduced substantial breaking changes to the
> language and isn't compatible. So use python 2.x, or if you're more
> ambitious fix the work in progress python3 branch and send a pull request.

**Comment by edyoung** [comment]
I wouldn't recommend that, it could have unexpected side effects on the rest of your system.  Easier to run "python2 setup.py build" and "python2 gnofract4d"

**Comment by Ravenmire** [comment]
I tried that, it worked.
And, you're correct. It is a better solution because of unintended side effects.
Fortunately, I haven't had any...yet. I've set python3 to be 'python'.

Ted, M∴ M∴
--

GnuPG/PGP key: 0xb07f9aae
Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by Ravenmire** [comment]
to create images like these with gnofract4d:
[20604165_1584632181558037_3620100317469017286_n.jpg][Blue spikes.jpg]

Ted, M∴ M∴
--

GnuPG/PGP key: 0xb07f9aae
Sent with [ProtonMail](https://protonmail.com) Secure Email.

>

**Comment by edyoung** [comment]
The latest release uses python3
